"""
webshell_ioc_forge.py — Scans web server access logs for webshell IOC patterns and
emits YARA/Sigma rule stubs for the highest-confidence indicator clusters found.

Usage:
    python webshell_ioc_forge.py access.log
    python webshell_ioc_forge.py access.log --format yara --min-hits 3
    python webshell_ioc_forge.py access.log --format sigma
    cat access.log | python webshell_ioc_forge.py /dev/stdin --format both
"""

import argparse
import re
import sys
from collections import defaultdict
from datetime import datetime, timezone


PATTERNS = {
    "eval_exec_chain": re.compile(
        r'(?:eval|exec|assert|preg_replace|call_user_func|passthru|system|popen|proc_open)'
        r'.*?(?:base64_decode|gzinflate|str_rot13|gzuncompress|rawurldecode)',
        re.IGNORECASE,
    ),
    "base64_blob": re.compile(
        r'(?:%[0-9A-Fa-f]{2}){8,}|[A-Za-z0-9+/]{40,}={0,2}',
    ),
    "webshell_filename": re.compile(
        r'/(?:c99|r57|cmd|shell|wso|b374k|weevely|alfa|adminer|p0wny)'
        r'(?:shell)?\.(?:php\d*|aspx?|jsp|phtml)\b',
        re.IGNORECASE,
    ),
    "suspicious_upload": re.compile(
        r'"(?:PUT|PATCH)\s+[^\s]+\.(?:php\d*|aspx?|jsp|phtml)\s',
        re.IGNORECASE,
    ),
    "anomalous_verb": re.compile(
        r'"(?:CONNECT|PROPFIND|SEARCH|TRACK|DEBUG)\s',
        re.IGNORECASE,
    ),
}

IP_RE = re.compile(r'^(\d{1,3}(?:\.\d{1,3}){3})')
STATUS_RE = re.compile(r'" (\d{3}) ')


def extract_indicators(lines):
    clusters = defaultdict(lambda: {"hits": 0, "ips": set(), "samples": []})
    ip_200_counts = defaultdict(int)
    ip_200_lines = defaultdict(list)

    for line in lines:
        ip_match = IP_RE.match(line)
        status_match = STATUS_RE.search(line)
        ip = ip_match.group(1) if ip_match else None
        status = status_match.group(1) if status_match else None

        if ip and status == "200":
            ip_200_counts[ip] += 1
            ip_200_lines[ip].append(line.rstrip())

        for name, pat in PATTERNS.items():
            if pat.search(line):
                clusters[name]["hits"] += 1
                if ip:
                    clusters[name]["ips"].add(ip)
                if len(clusters[name]["samples"]) < 3:
                    clusters[name]["samples"].append(line.rstrip()[:200])

    for ip, count in ip_200_counts.items():
        if count >= 20:
            key = "rapid_sequential_200s"
            clusters[key]["hits"] += 1
            clusters[key]["ips"].add(ip)
            if len(clusters[key]["samples"]) < 3:
                clusters[key]["samples"].append(ip_200_lines[ip][0][:200])

    return clusters


YARA_TMPL = """\
rule Webshell_{name} {{
    meta:
        description = "Webshell IOC cluster: {name} — auto-generated by webshell_ioc_forge"
        date = "{date}"
        hits = {hits}
        confidence = "{confidence}"
    strings:
{strings_block}
    condition:
        any of them
}}
"""

SIGMA_TMPL = """\
title: Webshell IOC — {name}
status: experimental
description: "Webshell IOC cluster: {name} — auto-generated by webshell_ioc_forge"
date: {date}
logsource:
    category: webserver
detection:
    keywords:
{keywords_block}
    condition: keywords
falsepositives:
    - Legitimate encoded parameters; raise --min-hits or add allowlist entries
level: high
"""

YARA_STRINGS = {
    "eval_exec_chain": ['$a = "eval" nocase', '$b = "base64_decode" nocase', '$c = "gzinflate" nocase'],
    "base64_blob": ['$a = /[A-Za-z0-9+\\/]{40,}={0,2}/', '$b = /%[0-9A-Fa-f]{2}/ wide ascii'],
    "webshell_filename": ['$a = "c99shell" nocase', '$b = "r57shell" nocase', '$c = "wso.php" nocase', '$d = "b374k" nocase'],
    "suspicious_upload": ['$a = "PUT" nocase', '$b = ".php" nocase', '$c = ".aspx" nocase'],
    "anomalous_verb": ['$a = "PROPFIND"', '$b = "CONNECT"', '$c = "TRACK"'],
    "rapid_sequential_200s": ['$a = "200"', '$b = /\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}/'],
}

SIGMA_KEYWORDS = {
    "eval_exec_chain": ["eval", "base64_decode", "gzinflate", "passthru"],
    "base64_blob": ["base64", "%2F%2F", "TVqQAAMA"],
    "webshell_filename": ["c99shell", "r57shell", "wso.php", "b374k", "p0wny"],
    "suspicious_upload": ["PUT *.php", "PATCH *.aspx", "PUT *.jsp"],
    "anomalous_verb": ["PROPFIND", "CONNECT", "TRACK", "SEARCH"],
    "rapid_sequential_200s": ["status=200"],
}


def confidence(hits):
    if hits >= 10:
        return "HIGH"
    if hits >= 5:
        return "MEDIUM"
    return "LOW"


def build_rules(clusters, fmt, min_hits):
    date = datetime.now(timezone.utc).date().isoformat()
    output = []
    ranked = sorted(clusters.items(), key=lambda x: x[1]["hits"], reverse=True)

    for name, data in ranked:
        if data["hits"] < min_hits:
            continue
        conf = confidence(data["hits"])
        strings = YARA_STRINGS.get(name, ['$a = "webshell"'])
        keywords = SIGMA_KEYWORDS.get(name, ["webshell"])

        if fmt in ("yara", "both"):
            strings_block = "\n".join(f"        {s}" for s in strings)
            output.append(YARA_TMPL.format(
                name=name, date=date, hits=data["hits"],
                confidence=conf, strings_block=strings_block,
            ))
        if fmt in ("sigma", "both"):
            keywords_block = "\n".join(f"        - '{k}'" for k in keywords)
            output.append(SIGMA_TMPL.format(
                name=name, date=date, keywords_block=keywords_block,
            ))
    return output


def print_summary(clusters, min_hits):
    print(f"{'Cluster':<30} {'Hits':>6}  {'IPs':>5}  {'Confidence':<10}")
    print("-" * 60)
    for name, data in sorted(clusters.items(), key=lambda x: x[1]["hits"], reverse=True):
        mark = "" if data["hits"] >= min_hits else "  [below threshold]"
        print(f"{name:<30} {data['hits']:>6}  {len(data['ips']):>5}  {confidence(data['hits']):<10}{mark}")


def main():
    ap = argparse.ArgumentParser(description="Webshell IOC Forge — YARA/Sigma stub generator from access logs")
    ap.add_argument("logfile", help="Path to plain-text web server access log")
    ap.add_argument("--format", choices=["yara", "sigma", "both"], default="both")
    ap.add_argument("--min-hits", type=int, default=2, metavar="INT")
    args = ap.parse_args()

    try:
        with open(args.logfile, errors="replace") as fh:
            lines = fh.readlines()
    except OSError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(2)

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    print(f"# webshell_ioc_forge | {ts} | log={args.logfile} lines={len(lines)} min-hits={args.min_hits} format={args.format}\n")

    clusters = extract_indicators(lines)
    if not clusters:
        print("No indicators found.", file=sys.stderr)
        sys.exit(1)

    print_summary(clusters, args.min_hits)
    print()

    rules = build_rules(clusters, args.format, args.min_hits)
    if not rules:
        print("No clusters met --min-hits threshold. Raise log volume or lower --min-hits.", file=sys.stderr)
        sys.exit(1)

    for rule in rules:
        print(rule)


if __name__ == "__main__":
    main()